server:
  port: 9091
  contextPath: /database
management:
  security:
    enabled: false
logging:
  level:
    org.springframework.security.web: debug


keycloak:
  configurationFile: classpath:config/keycloak-main.json