server:
  port: 9091
  contextPath: /database
management:
  security:
    enabled: false
logging:
  level:
    org.springframework.security.web: debug

keycloak.server.url: http://localhost:8095/auth
#
#keycloak:
#  configurationFile: classpath:config/keycloak-main.json